import type { IconType } from "react-icons";
import {
  IoAirplaneOutline,
  IoBalloonOutline,
  IoBandageOutline,
  IoBarbellOutline,
  IoBasketballOutline,
  IoBedOutline,
  IoBicycleOutline,
  IoBoatOutline,
  IoBookOutline,
  IoBriefcaseOutline,
  IoBrushOutline,
  IoBuildOutline,
  IoBulbOutline,
  IoCafeOutline,
  IoCalculatorOutline,
  IoCalendarClearOutline,
  IoCallOutline,
  IoCameraOutline,
  IoCarSportOutline,
  IoCartOutline,
  IoCashOutline,
  IoChatbubblesOutline,
  IoCodeSlashOutline,
  IoColorPaletteOutline,
  IoDocumentTextOutline,
  IoEarthOutline,
  IoFilmOutline,
  IoFitnessOutline,
  IoFlaskOutline,
  IoFlowerOutline,
  IoGameControllerOutline,
  IoGiftOutline,
  IoHammerOutline,
  IoHeartOutline,
  IoHomeOutline,
  IoLanguageOutline,
  IoLaptopOutline,
  IoLeafOutline,
  IoLibraryOutline,
  IoMailOutline,
  IoMedicalOutline,
  IoMegaphoneOutline,
  IoMicOutline,
  IoMoonOutline,
  IoMusicalNotesOutline,
  IoNewspaperOutline,
  IoNutritionOutline,
  IoPawOutline,
  IoPencilOutline,
  IoPeopleOutline,
  IoRestaurantOutline,
  IoRocketOutline,
  IoSchoolOutline,
  IoShirtOutline,
  IoSparklesOutline,
  IoSunnyOutline,
  IoTerminalOutline,
  IoTrendingUpOutline,
  IoTrophyOutline,
  IoTvOutline,
  IoWalkOutline,
  IoWalletOutline,
  IoWaterOutline,
} from "react-icons/io5";

export type CategoryIconOption = {
  id: string;
  label: string;
  keywords: string[];
  Icon: IconType;
};

export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = [
  {
    id: "briefcase",
    label: "Work",
    keywords: ["job", "office", "career"],
    Icon: IoBriefcaseOutline,
  },
  {
    id: "home",
    label: "Home",
    keywords: ["house", "chores", "family"],
    Icon: IoHomeOutline,
  },
  {
    id: "school",
    label: "School",
    keywords: ["class", "study", "college"],
    Icon: IoSchoolOutline,
  },
  {
    id: "book",
    label: "Reading",
    keywords: ["learn", "read", "books"],
    Icon: IoBookOutline,
  },
  {
    id: "library",
    label: "Research",
    keywords: ["notes", "writing", "reference"],
    Icon: IoLibraryOutline,
  },
  {
    id: "code",
    label: "Coding",
    keywords: ["dev", "software", "programming"],
    Icon: IoCodeSlashOutline,
  },
  {
    id: "laptop",
    label: "Computer",
    keywords: ["digital", "screen", "online"],
    Icon: IoLaptopOutline,
  },
  {
    id: "calendar",
    label: "Planning",
    keywords: ["schedule", "routine", "events"],
    Icon: IoCalendarClearOutline,
  },
  {
    id: "cash",
    label: "Finance",
    keywords: ["money", "budget", "bills"],
    Icon: IoCashOutline,
  },
  {
    id: "heart",
    label: "Health",
    keywords: ["wellness", "self care", "care"],
    Icon: IoHeartOutline,
  },
  {
    id: "medical",
    label: "Medical",
    keywords: ["doctor", "appointment", "meds"],
    Icon: IoMedicalOutline,
  },
  {
    id: "barbell",
    label: "Workout",
    keywords: ["gym", "exercise", "training"],
    Icon: IoBarbellOutline,
  },
  {
    id: "fitness",
    label: "Fitness",
    keywords: ["run", "cardio", "movement"],
    Icon: IoFitnessOutline,
  },
  {
    id: "flower",
    label: "Personal",
    keywords: ["life", "self", "growth"],
    Icon: IoFlowerOutline,
  },
  {
    id: "people",
    label: "Social",
    keywords: ["friends", "family", "community"],
    Icon: IoPeopleOutline,
  },
  {
    id: "music",
    label: "Music",
    keywords: ["creative", "practice", "audio"],
    Icon: IoMusicalNotesOutline,
  },
  {
    id: "palette",
    label: "Creative",
    keywords: ["design", "art", "maker"],
    Icon: IoColorPaletteOutline,
  },
  {
    id: "build",
    label: "Errands",
    keywords: ["repair", "maintenance", "admin"],
    Icon: IoBuildOutline,
  },
  {
    id: "car",
    label: "Travel",
    keywords: ["commute", "drive", "trip"],
    Icon: IoCarSportOutline,
  },
  {
    id: "gamepad",
    label: "Fun",
    keywords: ["hobby", "play", "games"],
    Icon: IoGameControllerOutline,
  },
  {
    id: "bulb",
    label: "Ideas",
    keywords: ["brainstorm", "think", "inspiration"],
    Icon: IoBulbOutline,
  },
  {
    id: "pencil",
    label: "Writing",
    keywords: ["journal", "draft", "blog"],
    Icon: IoPencilOutline,
  },
  {
    id: "document",
    label: "Documents",
    keywords: ["paperwork", "forms", "admin"],
    Icon: IoDocumentTextOutline,
  },
  {
    id: "newspaper",
    label: "News",
    keywords: ["articles", "current events", "media"],
    Icon: IoNewspaperOutline,
  },
  {
    id: "language",
    label: "Languages",
    keywords: ["translate", "vocabulary", "speaking"],
    Icon: IoLanguageOutline,
  },
  {
    id: "calculator",
    label: "Math",
    keywords: ["numbers", "homework", "accounting"],
    Icon: IoCalculatorOutline,
  },
  {
    id: "flask",
    label: "Science",
    keywords: ["lab", "experiment", "chemistry"],
    Icon: IoFlaskOutline,
  },
  {
    id: "terminal",
    label: "Terminal",
    keywords: ["shell", "devops", "server"],
    Icon: IoTerminalOutline,
  },
  {
    id: "rocket",
    label: "Projects",
    keywords: ["launch", "startup", "side project"],
    Icon: IoRocketOutline,
  },
  {
    id: "trending",
    label: "Growth",
    keywords: ["goals", "metrics", "progress"],
    Icon: IoTrendingUpOutline,
  },
  {
    id: "trophy",
    label: "Goals",
    keywords: ["achievement", "win", "milestone"],
    Icon: IoTrophyOutline,
  },
  {
    id: "megaphone",
    label: "Marketing",
    keywords: ["promotion", "announce", "outreach"],
    Icon: IoMegaphoneOutline,
  },
  {
    id: "mail",
    label: "Email",
    keywords: ["inbox", "messages", "reply"],
    Icon: IoMailOutline,
  },
  {
    id: "call",
    label: "Calls",
    keywords: ["phone", "meeting", "contact"],
    Icon: IoCallOutline,
  },
  {
    id: "chat",
    label: "Chat",
    keywords: ["conversation", "messages", "talk"],
    Icon: IoChatbubblesOutline,
  },
  {
    id: "wallet",
    label: "Spending",
    keywords: ["purchases", "expenses", "wallet"],
    Icon: IoWalletOutline,
  },
  {
    id: "cart",
    label: "Shopping",
    keywords: ["groceries", "buy", "store"],
    Icon: IoCartOutline,
  },
  {
    id: "gift",
    label: "Gifts",
    keywords: ["birthday", "holiday", "present"],
    Icon: IoGiftOutline,
  },
  {
    id: "restaurant",
    label: "Meals",
    keywords: ["cook", "food", "dinner"],
    Icon: IoRestaurantOutline,
  },
  {
    id: "nutrition",
    label: "Nutrition",
    keywords: ["diet", "healthy", "produce"],
    Icon: IoNutritionOutline,
  },
  {
    id: "cafe",
    label: "Coffee",
    keywords: ["cafe", "break", "meetup"],
    Icon: IoCafeOutline,
  },
  {
    id: "water",
    label: "Hydration",
    keywords: ["drink", "water", "habit"],
    Icon: IoWaterOutline,
  },
  {
    id: "bed",
    label: "Sleep",
    keywords: ["rest", "nap", "bedtime"],
    Icon: IoBedOutline,
  },
  {
    id: "moon",
    label: "Evening",
    keywords: ["night", "wind down", "relax"],
    Icon: IoMoonOutline,
  },
  {
    id: "sunny",
    label: "Morning",
    keywords: ["sun", "day", "outdoors"],
    Icon: IoSunnyOutline,
  },
  {
    id: "sparkles",
    label: "Self Care",
    keywords: ["skincare", "pamper", "clean"],
    Icon: IoSparklesOutline,
  },
  {
    id: "bandage",
    label: "Recovery",
    keywords: ["injury", "rehab", "heal"],
    Icon: IoBandageOutline,
  },
  {
    id: "walk",
    label: "Walking",
    keywords: ["steps", "stroll", "hike"],
    Icon: IoWalkOutline,
  },
  {
    id: "bicycle",
    label: "Cycling",
    keywords: ["bike", "ride", "commute"],
    Icon: IoBicycleOutline,
  },
  {
    id: "basketball",
    label: "Sports",
    keywords: ["team", "practice", "game"],
    Icon: IoBasketballOutline,
  },
  {
    id: "leaf",
    label: "Nature",
    keywords: ["garden", "plants", "outdoors"],
    Icon: IoLeafOutline,
  },
  {
    id: "paw",
    label: "Pets",
    keywords: ["dog", "cat", "vet"],
    Icon: IoPawOutline,
  },
  {
    id: "shirt",
    label: "Laundry",
    keywords: ["clothes", "wardrobe", "outfit"],
    Icon: IoShirtOutline,
  },
  {
    id: "hammer",
    label: "DIY",
    keywords: ["fix", "tools", "project"],
    Icon: IoHammerOutline,
  },
  {
    id: "brush",
    label: "Art",
    keywords: ["paint", "draw", "sketch"],
    Icon: IoBrushOutline,
  },
  {
    id: "camera",
    label: "Photography",
    keywords: ["photo", "shoot", "pictures"],
    Icon: IoCameraOutline,
  },
  {
    id: "film",
    label: "Movies",
    keywords: ["film", "watch", "video"],
    Icon: IoFilmOutline,
  },
  {
    id: "tv",
    label: "Shows",
    keywords: ["tv", "streaming", "watch"],
    Icon: IoTvOutline,
  },
  {
    id: "mic",
    label: "Podcast",
    keywords: ["record", "voice", "speaking"],
    Icon: IoMicOutline,
  },
  {
    id: "balloon",
    label: "Events",
    keywords: ["party", "celebration", "birthday"],
    Icon: IoBalloonOutline,
  },
  {
    id: "airplane",
    label: "Flights",
    keywords: ["vacation", "airport", "abroad"],
    Icon: IoAirplaneOutline,
  },
  {
    id: "boat",
    label: "Leisure",
    keywords: ["boat", "weekend", "getaway"],
    Icon: IoBoatOutline,
  },
  {
    id: "earth",
    label: "Volunteering",
    keywords: ["community", "charity", "environment"],
    Icon: IoEarthOutline,
  },
];

const ICONS_BY_ID = new Map(
  CATEGORY_ICON_OPTIONS.map((option) => [option.id, option]),
);

export function getCategoryIconOption(
  iconId: string | undefined,
): CategoryIconOption | undefined {
  if (!iconId) return undefined;
  return ICONS_BY_ID.get(iconId);
}

export function renderCategoryIcon(
  iconId: string | undefined,
  className = "h-3.5 w-3.5",
) {
  if (!iconId) return null;
  const option = getCategoryIconOption(iconId);
  if (option) return <option.Icon className={className} aria-hidden />;
  return <span aria-hidden>{iconId}</span>;
}
